version: '3.8'

services:
  image-postgres:
    image: postgres:latest
    container_name: image-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9320
      POSTGRES_DB: image_service_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    volumes:
      - image_postgres_data:/var/lib/postgresql/data
    networks:
      - support-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: supersecurepassword
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9000:9000"
      - "9003:9003"
    command: server /data --console-address ":9003"
    volumes:
      - minio_data:/data
    networks:
      - support-network

  image-service:
    build:
      context: ../../SupportDesk-ImageService
      dockerfile: Dockerfile
    container_name: image-service
    ports:
      - "8082:8082"
      - "50051:50051"
    depends_on:
      - image-postgres
      - minio
    networks:
      - support-network

volumes:
  image_postgres_data:
  minio_data:

networks:
  support-network:
    external: true
    name: support-network
